### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by jpzeballosr** [MatthiasZbinden/MSOfficeTools#2]
Hi Matthias, top stuff, thanks for sharing this tool. The current tool seems not to address/modify text in charts/graphs, I tried to modify the macro code to include charts, but the command 'Language ID' seems not to be available for text components of charts (title, axes and legend). Thoughts?
PD. looking forward to seeing the slide master piece soon. 
Regards
JP

**Comment by MatthiasZbinden** [comment]
Hi

thanks for your compliment and input and sorry for my bad response time.
Actually I am not so active for private reasons (family, kids, house repair, garden...), but I was programming a lot in the 90ies and 00s (VBA, Object Pascal, C++, Web) and offering my tools to others back then. This thing here I made during work because I needed it, and I saw many others need it apparently. So I created this GitHub account.

But I only can spend time on it in free slots. Currently, I am reordering the code (changes are still uncommitted), because it's the same code in many places, and in the end it boils down into some recursive loops (because a Shapes list can have e.g. a Chart, and then the Chart can have Shapes again...) which needs to be applied to a few places.
I was about to test your question, I created a chart with a spelling mistake, and I can select it and put a language, so there must be a command for it. I wanted to record a macro and do it, then check the code, but it seems my company has now disabled the capability to record macros...maybe you can try it.
The same I wanted to do for the Master Slides. Once you see in the recorded Macro where you need to go, it's just applying the loop to the Shapes collection.

Hope you can be a bit patient with me until I manage to finish
Kind regards
Matthias

**Comment by MatthiasZbinden** [comment]
Chart support added. Not yet stable. Some chart types do not offer all Object Members I want to access and then crash. I don't know any nice way of checking this, apart from On Error Go To.
Kindly try with your presentations.

**Comment by jpzeballosr** [comment]
Massive thanks Matthias for taking the time! amazing contribution!. I've tested this new version, first, it seems to work perfectly with slide master changes. Second, in terms of charts, I just realised power point doesn't seem to support spell checking to chart elements (except for chart tittles). Third, your version works well with shapes and charts grouped together, so that's awesome.

A nice next improvement can be creating an add-in to the ribbon, so you don't have to open an additional ppt file. I'll explore this new feature, any thoughts?

**Comment by MatthiasZbinden** [comment]
> your version works well with shapes and charts grouped together, so that's awesome.

Thank you very much for the thorough testing! I had no time for that, but that's the most valuable thing!

> Massive thanks Matthias for taking the time! amazing contribution!. I've tested this new version, first, it seems to work perfectly with slide master changes.

You're welcome, and thanks for your support. Again, it seems to be a web-wide problem, the language-thing with PPT...

>  in terms of charts, I just realised power point doesn't seem to support spell checking to chart elements (except for chart tittles)

I found spell check is done in Titles, Axis Labels and Text Fields inside the Chart

> A nice next improvement can be creating an add-in to the ribbon, so you don't have to open an additional ppt file. I'll explore this new feature, any thoughts?

Yes, as presentation it's annoying. Was quick & dirty. I did an Add-On for Gas Turbines when Office was not yet the 365 version, with the good old *.ppa file. I even added a custom ribbon with tons of functions and pictures. However, I have not been keeping me up-to-date on how to properly write add-ins nowadays, as my main job is mechanical engineer, not IT. I quickly checked the developer page of MS, but I did not spot instantly a straight-forward example or so. If you have one, that'd be helpful!

*Remark*: I will close the issue, as apparently it has been resolved, and the add-on is a feature request.
